### ISSUE TITLE
Dark, Weekday and weekend seem modifiable

### ISSUE THREAD

**Issue by jaller94** [tomasy/date-time-adapter#10]
The properties dark, Weekday and weekend do not seem to be modifiable.
Why is readOnly not set to True and in the case of Weekday explicitly set to False?

**Comment by tomasy** [comment]
If you check in README I have tried to explain, but there is a bug in rule-engine in mozilla-iot. See issue mozilla-iot/gateway#1452. To make some properties changeable is a workaround.

**Comment by tomasy** [comment]
@jaller94 Is my answer good enough?

**Comment by jaller94** [comment]
It's good to know the reason. I had not seen the explanation in the ReadMe.

I understand the conflict of making this work with the Mozilla Things gateway vs. staying true to the Web of Things Spec.
Hope the issue gets resolved soon. 👍

**Comment by tomasy** [comment]
i will check if this is corrected in 0.8 of Mozilla
