### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by flatsiedatsie** [tomasy/date-time-adapter#11]
How mysterious!

**Comment by tomasy** [comment]
The code is not in github. I use another repo that is private and I have not spent time to keep both in sync. The code is in the release package so it is not hidden.
If there is a wish I can see how to do this in the simplest way

**Comment by tomasy** [comment]
I think I have figured out how to make it possible to sync my original repo with this on github.
I have added a new branch 'release' which contains the code when I do a release.

**Comment by flatsiedatsie** [comment]
Great!
