### ISSUE TITLE
error after setting long lat

### ISSUE THREAD

**Issue by vincentserpoul** [tomasy/date-time-adapter#13]
2019-05-11 08:03:21.069 ERROR  : date-time: Unexpected source: state=5 source=1 action=5 (src/transports/utils/streamhdr.c:306)
2019-05-11 08:03:21.077 INFO   : Plugin: date-time-adapter died, code = null restarting...

**Comment by tomasy** [comment]
I need some more info.
version datetimeadapter:
version gateway:
timezone:
lat:
long:
Is it still restarting? Can you reproduce the problem? 
If possible, send relevant part from logfile

**Comment by vincentserpoul** [comment]
my bad: 
version datetimeadapter: 1.0.0
version gateway: 0.8.1
timezone: Asia/Singapore
lat: 1.1911822
long: 103.8553671

I restarted my gateway, and it's working now, no more error. Unfortunately, I can't reproduce it anymore :/.
Unfortunately, I have no better logs
