### ISSUE TITLE
How do I confirm sunrise/sunset times?

### ISSUE THREAD

**Issue by hwine** [tomasy/date-time-adapter#2]
Is there a way I can see the calculated times (sunrise/sunset), so I can debug my settings?

I actually figured out (at least part of) my issue -- I'm west longitude, and had forgotten to use a negative value. But still, the horizon settings are a bit tricky...

**Comment by tomasy** [comment]
Good point. I will add it to README.
For the moment you need too go to `Settings` -> `Developer` -> `View Logs` -> `run-app.log` and the search for a line that looks like `sunrise will happen in`  and as an example you will get
`sunrise will happen in 17:55:20.881772 at 2018-11-12 07:45:23.299329+01:00` so sunrise will be at  `07:45`

About the horizon. When the sunset/sunrise appear it will still not dark. So the horizon say how much below the sun is when we as human think it is dark. Start with `-0:34`.

**Comment by hwine** [comment]
That works great -- thanks!
