### ISSUE TITLE
Verison 1.0.1 faile on install in Mozilla Web Things Gateway

### ISSUE THREAD

**Issue by ZR-candle** [tomasy/date-time-adapter#20]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
        __import__(vendored_name, globals(), locals(), level=0)
  ModuleNotFoundError: No module named 'pip._vendor.pkg_resources'
During handling of the above exception, another exception occurred:
   Traceback (most recent call last):
   File "/usr/lib/python3.7/pkgutil.py", line 415, in get_importer
      importer = sys.path_importer_cache[path_item]
   KeyError: ''

**Comment by tomasy** [comment]
Hm...
Please can you send me some more information
Was this a new installation or an upgrade fo DateTime Adapter?
Version of Mozilla Web Things Gateway:___
Platform for Mozilla Web Things Gateway? Raspberry?

**Comment by ZR-candle** [comment]
Hi,
        This was an upgrade to the Date Time Adapter
    Verison of Mozilla Web Things Gateway: 0.11.0 dated Feb 18 2020
    Platform: Raspberry Pi
    
    
    On 25/02/2020 19:30, tomasy wrote:
    
    
      
      Hm...
        Please can you send me some more information
        Was this a new installation or an upgrade fo DateTime Adapter?
        Version of Mozilla Web Things Gateway:___
        Platform for Mozilla Web Things Gateway? Raspberry?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tomasy/date-time-adapter/issues/20?email_source=notifications\u0026email_token=AODGRZ3WSFILTN56MW5SKQTREVWXHA5CNFSM4K3ODYRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM5F23I#issuecomment-591027565",
"url": "https://github.com/tomasy/date-time-adapter/issues/20?email_source=notifications\u0026email_token=AODGRZ3WSFILTN56MW5SKQTREVWXHA5CNFSM4K3ODYRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM5F23I#issuecomment-591027565",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tomasy** [comment]
I also upgrade my installation in the same way with out any problem.
If you reboot your pi and then check the log in "Settings" -> "Developer" -> "View Internal Logs" 
Do you get some more information? Will the problem occur immediately or after some time?
DateTime Adapter uses the following python modules "jsonschema", "pyephem" and "pytz" but they must be installed.

**Comment by mrstegeman** [comment]
I saw this same issue on another gateway a few days ago... It was an RPi that had initially been flashed with Raspbian Stretch about 2 years ago, and somehow got severely corrupted. The only way to fix it was to reflash with a new gateway image.

**Comment by tomasy** [comment]
@ZR-candle I close the issue, if you need help reopen it.
