### ISSUE TITLE
Error "undefined 400" after configuring add-on

### ISSUE THREAD

**Issue by foodev** [tomasy/date-time-adapter#24]
I just installed the latest version 1.0.1 and after I wanted to save my configuration I got and error "undefined 400". In the log file I found the following:
```
2020-05-10 12:43:10.868 ERROR  : Failed to restart add-on date-time-adapter
2020-05-10 12:43:10.872 ERROR  : TypeError: Cannot read property 'send' of undefined
    at Plugin.sendMsg (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:580:1)
    at Plugin.unload (/home/pi/mozilla-iot/gateway/build/webpack:/src/plugin/plugin.js:737:1)
    at AddonManager.unloadAddon (/home/pi/mozilla-iot/gateway/build/webpack:/src/addon-manager.js:963:1)
    at ./src/controllers/addons_controller.js.AddonsController.put (/home/pi/mozilla-iot/gateway/build/webpack:/src/controllers/addons_controller.js:111:1)
```

**Comment by foodev** [comment]
Hmm, sorry for the confusion but just after I created this issue I tried to save it again out of curiosity and now it worked. I have no idea why...

**Comment by darrenwinslow** [comment]
Same Issue.  Also does not show up in rules.

**Comment by tomasy** [comment]
The error seems to be "outside" of date-time-adapter. When did this happen, fresh installation or an upgrade of the whole gateway? Is everything else OK? Have you tried to restart the gateway?

**Comment by bnjroos** [comment]
Same issue.

**Comment by bnjroos** [comment]
Need to add the datetime thing to be able to configure the addon.

**Comment by tomasy** [comment]
> Need to add the datetime thing to be able to configure the addon.
Is the problem solved?

**Comment by gpambrozio** [comment]
Getting this as well. Already restarted the gateway and still doesn't work.

> Need to add the datetime thing to be able to configure the addon
@bnjroos I don't see a thing for datetime. Are you referring to some other addon?

**Comment by tomasy** [comment]
> Getting this as well. Already restarted the gateway and still doesn't work.
> 
> > Need to add the datetime thing to be able to configure the addon
> > @bnjroos I don't see a thing for datetime. Are you referring to some other addon?

Please add more info. 
When did this happen? Do you have logs?

**Comment by gpambrozio** [comment]
Here are some redacted logs with just this add on activity. It's working now. Seems like it took a really long time to install, maybe the logs will show you why.

I have a Pi B+ so not the fastest one but still.... My internet connection is fast, should not be an issue.

[run-app.log.txt](https://github.com/tomasy/date-time-adapter/files/4742691/run-app.log.txt)

**Comment by tomasy** [comment]
> Here are some redacted logs with just this add on activity. It's working now. Seems like it took a really long time to install, maybe the logs will show you why.
> 
> I have a Pi B+ so not the fastest one but still.... My internet connection is fast, should not be an issue.
> 
> [run-app.log.txt](https://github.com/tomasy/date-time-adapter/files/4742691/run-app.log.txt)

It is working. A restart solved the problem
