### ISSUE TITLE
DateTime Adapter is not visible in Add Thing screen

### ISSUE THREAD

**Issue by astrojolo** [tomasy/date-time-adapter#25]
I have a fresh installation of Mozilla IOT on RPi 3 - version 0.12.0. I have successfully added SystemInfo add-on and also local NodeMCU device with LED lamp example. 
I also added DateTime Adapter to add-on and configured it with values:
TZ: Europe/Warsaw
Lat: 50.14
Lon: 18.36
Horizon: -6
Log level: INFO

Unfortunately, the add-on is not visible at Things screen after pressing the + button. I checked the developer logs and it seems it tries to install some dependencies, but it takes quite a long time - already 15 minutes. I attached log entries.

I tried to enable/disable the addon, remove and add it again (settings were preserved), and also reboot the RPi gateway.

[run-app.log.txt](https://github.com/tomasy/date-time-adapter/files/4876018/run-app.log.txt)

**Comment by astrojolo** [comment]
I checked in the morning and eventually DateTime Adapter installed and is now visible in the Thing board. I attach an updated log file. It is also visible in the Rules screen and rule can be set. So it was only installing quite long and now work. 

[run-app.log.txt](https://github.com/tomasy/date-time-adapter/files/4877187/run-app.log.txt)

**Comment by tomasy** [comment]
Good to hear.
