### ISSUE TITLE
Better explanation

### ISSUE THREAD

**Issue by Mikro007** [tomasy/date-time-adapter#3]
Better explanation about what to enter in the field:
Horizon e.f. '-0:34' or -6=civil twilight, -12=nautical, -18=astronomical

**Comment by tomasy** [comment]
Actual sunrise corresponds to the time when the edge of the Sun appears (or disappears, for sunset) just above/below the horizon (0 degree). Some organizations use `-0:34` (34 minutes before sunrise or 34 minutes after sunset). -`12` is 12 degrees below the horizon, used in nautical (ships).

**Comment by Mikro007** [comment]
Ok, unfortunately not so userfriendly.

So if I write 1:00 or 0:60 without minus it will be the same as an hour before sunset?

**Comment by tomasy** [comment]
Sorry, misunderstanding from my site. `-0:34` is 34 arcminutes below horizon. So you need to experiment for the correct value.

**Comment by tomasy** [comment]
Check on https://www.timeanddate.com/sun/ and after select place, select "Sunrise & Sunset" to see the difference between `-0:34' or `-6`=civil twilight, `-12`=nautical and `-18`=astronomical

**Comment by Mikro007** [comment]
I don´t get it.

I understand the difference between: civil, nautical and astronomical. 

But how do I get BEFORE sunset? All these is AFTER sunset...

**Comment by Mikro007** [comment]
I found a good picture of golden hour that Im looking for.

![golden](https://user-images.githubusercontent.com/22572811/48721264-d4056780-ec21-11e8-8540-d3e8f996be98.png)

**Comment by tomasy** [comment]
Yes, you need to experiment and use a positive value instead.
I hope this will solve your problem

**Comment by tomasy** [comment]
Close this. If still problem please reopen
