### ISSUE TITLE
Strange sunset

### ISSUE THREAD

**Issue by Mikro007** [tomasy/date-time-adapter#4]
I want to have a good sunset time and recently a strange thing happened. As you can see the sunset in the log should be 15:35. But in reality it turned out instead at 16:25?

`sunset will happen in 23:28:06.416824 at 2018-11-19 15:35:49.500802+01:00`

My rule looks like this:
![sunset](https://user-images.githubusercontent.com/22572811/48674724-b8319100-eb4f-11e8-9419-1e11e3d9a511.png)

How can I for example set X minutes before sunset?

**Comment by tomasy** [comment]
1. About the `15:35` and `16:35` Check if the timezone for the gateway is the same timezone you have configured for date-time-adapter. 
1. _To set X minutes before the sunset._  Check the `horizon` in configuration for DateTime.  The normal configuration is `-0.34`and this will activate sunset 34 minutes after the sun has disappered under the horizon. Check https://rhodesmill.org/pyephem/

I hope this will solve your problem

**Comment by Mikro007** [comment]
How do I change timezone in the gateway?

**Comment by tomasy** [comment]
I assume you have a raspberry. Login to it with ssh and execute `timedatectl` Check if the output for Time zone is correct.

**Comment by Mikro007** [comment]
I did a check on the rpi time and that was wrong. Changed timezone in the configuration `sudo raspi-config` and did a reboot.

Still the sunset says one hour later in the log file. Is this Horizon settings problem?

**Comment by tomasy** [comment]
What time is wrong? If you use the clock instead of DateTime and set a time. Will Kontor turn on at correct time?
For the value horizon. If you set horizon to `-0:34` and then use for example https://www.timeanddate.com/sun/. The value shall differ just some minutes. Have you checked in real when `Kontor`is switched on?

**Comment by tomasy** [comment]
Close this. If still problem please reopen
