### ISSUE TITLE
Add sources under version control

### ISSUE THREAD

**Issue by rzr** [tomasy/date-time-adapter#5]
Hi,
I noticed that sources are not pushed only readme file, is this intentional ? why?

https://github.com/tomasy/date-time-adapter/releases

Well one could look at python scripts in tarball:
https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/date-time-adapter-0.9.5.tgz

Regards

**Comment by tomasy** [comment]
I have all my projects on my own server. Source code is also uploaded in the tarball on git hub under releases.

**Comment by jaller94** [comment]
Adding the code into the Git repository would allow others to collaborate on the project more easily.
It would also allow to permalink to files and lines of the source for issues.

Please consider uploading the source to the repository.

**Comment by rzr** [comment]
Just for curiosity why using github ?

For linking may this fork help:
https://github.com/TizenTeam/date-time-adapter/tree/sandbox/rzr/devel/master

**Comment by jaller94** [comment]
GitLab, Gitea or so would work just as well.
The ReadMe file has no Contributing section to point to other channels to send Pull Requests (PRs). And with the source not being in the repo, sending PRs is unreasonable.

**Comment by tomasy** [comment]
I think I have figured out how to make it possible to sync my original repo with this on github.
I have added a new branch 'release' which contains the code when I do a release.
