### ISSUE TITLE
Slow to apply configuration changes

### ISSUE THREAD

**Issue by nmacgreg** [tomasy/date-time-adapter#6]
I added the DateTime Add-on, then scanned for new Things, found it, added it.  About 10 days later, after fooling with it, I finally decided the TZ was incorrect and there ought to be a way to fix/set that.  I went back to Add-Ons, punched Configure, and yes, it's set to UTC.  This device is in Edmonton, Canada, so MST (Mountain Standard Time) ought be the correct value.  I set it to MST, and punched "Apply".  The button changed to "Applying..." and stayed that way for a Very Long Time, more than a minute.  It finally displayed an error message, "undefined NetworkError when attempting to fetch resource."  Also, the error message was poorly formatted, overlapping the "Configuration for sunset and sunrise" text.  I'm using it from outside my home network, on campus, on a wired network in my office (so, great networks here).

Returning to the Things view, the DateTime thing is greyed out, so I deleted it, re-scanned, ... and failed to find a replacement.

I went back to the Config panel for the Add-on, changed it back to UTC, this time with a stopwatch running, and it took 2:00 exactly, this time with the message, "undefined Failed to fetch".  I tried again, setting it back to MST, and it worked, dumping the display quickly (5s?) to the Add-ons page. Back in the Things view, I was able to discover the new Thing, and the time displayed is now correct.  So, I got it working, but it was painful.

The Mozilla IoT gateway was installed about 2 weeks ago, v0.6.1.  It was a fresh install on a RasPi 3. 

I'm using an ancient Firefox v50.1.0, on a Fedora . Tried also on ancient Chrome Version 54.0.2840.100 (64-bit).  And on my phone, Android 8.1.0, everything up to date (Nexus 6P, Nov 5 update), in the progressive web app, where I simply gave up waiting after more than 5 minutes.  At the about the 20 minute-mark I checked back: it had finally failed with the "undefined Failed to fetch" message, ditto formatting errors

Could the default not be the local TZ of the base OS?

**Comment by tomasy** [comment]
About the timezone. Please make a try with "America/Edmonton". 

After the timezone  is changed restart the gateway (just to make logs file shorter) and then check for errors in the log file and send them to me.
To find the time for sunrise/sunset check https://github.com/tomasy/date-time-adapter#find-calculated-sunset-and-sunrise-time

**Comment by tomasy** [comment]
Is this still an issue?

**Comment by tomasy** [comment]
No response. If still problem, please reopen
