### ISSUE TITLE
Feature Request: Day of Week

### ISSUE THREAD

**Issue by doscott** [tomasy/date-time-adapter#8]
This is a nice tool. It would be great to have two additional properties:
Day (similar to Hour)
Day_N (similar to Hour_n)

where the day value is 0 through 6 with 0 - 4 being Monday through Friday so that a rule of Day_N < 5  would be equivalent to weekday.

**Comment by tomasy** [comment]
I am just waiting for the next release, 0.7, of the gateway. In that release they have fixed some bugs so I can use enums for days and they will be presented in a dropdown list. Much eaiser for the user.
I have implemented "Weekday" (Monday,...) and there is also a property for "Weekend" (Sat, - sunday) and "NOT Weekend" (Monday - Friday).
Do you think "Day_N" is needed? if the property "Weekend" exist?

If you want to test, update the gateway to pre 0.7 status and I can upload a new version of date-time-adapter.

**Comment by doscott** [comment]
I don’t think Day_N would be required if Weekday and Weekend are implemented. I don’t see a need for “NOT Weekend”.

I will wait for the 0.7 release.

**Comment by tomasy** [comment]
In latest release
